export enum MessageType {
  QUERY_LATEST_BLOCK = 0,
  QUERY_ALL_BLOCKS = 1,
  RESPONSE_BLOCKCHAIN = 2,
  QUERY_PEERS = 3,
  RESPONSE_PEERS = 4,
  KEEP_ALIVE = 5,
  QUERY_PEER_ADDRESS = 6,
  RESPONSE_PEER_ADDRESS = 7,
}
